/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 Surface, Background & Text Tokens (Dynamic Light/Dark)
        "surface": "var(--color-surface, #10131a)",
        "surface-dim": "var(--color-surface-dim, #10131a)",
        "surface-bright": "var(--color-surface-bright, #363941)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #0b0e15)",
        "surface-container-low": "var(--color-surface-container-low, #191c22)",
        "surface-container": "var(--color-surface-container, #1d2027)",
        "surface-container-high": "var(--color-surface-container-high, #272a31)",
        "surface-container-highest": "var(--color-surface-container-highest, #32353c)",
        "surface-variant": "var(--color-surface-container-highest, #32353c)",
        "background": "var(--color-background, #10131a)",
        "on-surface": "var(--color-on-surface, #e0e2ec)",
        "on-surface-variant": "var(--color-on-surface-variant, #b9cbbe)",
        "outline": "var(--color-outline, #849589)",
        "outline-variant": "var(--color-outline-variant, #3b4a40)",
        "on-background": "var(--color-on-background, #e0e2ec)",
        "inverse-surface": "var(--color-on-surface, #e0e2ec)",
        "inverse-on-surface": "var(--color-surface, #10131a)",

        // Dynamic Accent Tokens (via PhotoshopColorPicker & colorDeriver)
        "secondary-fixed": "#ffdea8",
        "on-primary": "var(--theme-on-primary, #003822)",
        "tertiary": "#d8f3ff",
        "primary-container": "var(--theme-primary-container, #00f0a0)",
        "on-tertiary-container": "#006379",
        "primary-fixed-dim": "var(--theme-primary-fixed-dim, #00e296)",
        "on-tertiary": "#003543",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#5e4200",
        "on-error-container": "#ffdad6",
        "secondary-container": "#feb700",
        "tertiary-fixed": "#b6ebff",
        "on-error": "#690005",
        "tertiary-container": "#82dfff",
        "on-secondary-container": "#6b4b00",
        "on-primary-fixed": "var(--theme-on-primary-fixed, #002112)",
        "on-secondary": "#412d00",
        "surface-tint": "var(--theme-primary-fixed-dim, #00e296)",
        "on-primary-container": "var(--theme-on-primary-container, #006843)",
        "primary-fixed": "var(--theme-primary-fixed, #4dffb2)",
        "secondary-fixed-dim": "#ffba20",
        "primary": "var(--theme-primary, #b6ffd4)",
        "on-primary-fixed-variant": "var(--theme-on-primary-fixed-variant, #005234)",
        "on-tertiary-fixed-variant": "#004e60",
        "inverse-primary": "#006c46",
        "on-secondary-fixed": "#271900",
        "error": "#ffb4ab",
        "secondary": "#ffdb9d",
        "on-tertiary-fixed": "#001f28",
        "tertiary-fixed-dim": "#47d6ff",

        fintech: {
          dark: '#10131a',
          card: '#191c22',
          surface: '#1d2027',
          border: '#3b4a40',
        },
        brand: {
          gcash: {
            DEFAULT: '#005CE6',
            dark: '#003B99',
            light: '#2A7FFF',
          },
          maya: {
            DEFAULT: '#00D66F',
            dark: '#064E3B',
            bg: '#052E16',
          },
          rcbc: {
            DEFAULT: '#0A3180',
            dark: '#00205B',
            accent: '#F59E0B',
          },
          bpi: {
            DEFAULT: '#8B0000',
            dark: '#5C0000',
            accent: '#D97706',
          },
          unionbank: {
            DEFAULT: '#EA580C',
            dark: '#9A3412',
            accent: '#FDBA74',
          },
          bdo: {
            DEFAULT: '#003366',
            dark: '#001F3F',
            accent: '#EAB308',
          },
          gotyme: {
            DEFAULT: '#0D9488',
            dark: '#115E59',
            accent: '#5EEAD4',
          },
          seabank: {
            DEFAULT: '#FF5722',
            dark: '#E64A19',
            accent: '#FFCCBC',
          },
        }
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "1.75rem",
        "gutter": "0.75rem",
        "margin": "1rem",
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Space Mono', 'JetBrains Mono', 'monospace'],
        "label-sm": ["Space Mono", "monospace"],
        "label-md": ["Space Mono", "monospace"],
        "label-lg": ["Space Mono", "monospace"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["9px", { "lineHeight": "12px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "label-md": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "26px", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      },
      boxShadow: {
        'wallet': '0 20px 35px -10px rgba(0, 0, 0, 0.5), 0 1px 3px 0 rgba(0, 0, 0, 0.3)',
        'glow-gcash': '0 0 30px -5px rgba(0, 92, 230, 0.35)',
        'glow-maya': '0 0 30px -5px rgba(0, 214, 111, 0.35)',
        'glow-rcbc': '0 0 30px -5px rgba(10, 49, 128, 0.4)',
        'glow-primary': '0 0 24px rgba(0, 240, 160, 0.45)',
        'pure-white': '0 0 40px rgba(255, 255, 255, 0.25)',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
